export const navLinks = [
  {
    id: '1',
    href: '/music',
    text: 'Music',
  },
  {
    id: '2',
    href: '/videos',
    text: 'Videos',
  },
  {
    id: '3',
    href: '/services',
    text: 'Services',
  },
  {
    id: '4',
    href: '/blog',
    text: 'Blog',
  },
  {
    id: '5',
    href: '/about',
    text: 'About',
  },
  {
    id: '6',
    href: '/contact',
    text: 'Contact',
  },
];

export const songs = [
  {
    id: '1',
    title: 'Anchor Point',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/anchor-point.mp3',
  },
  {
    id: '2',
    title: 'Brain Freeze',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Brain-Freeze.mp3',
  },
  {
    id: '3',
    title: 'Breaking The Chains',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Breaking-the-Chains.mp3',
  },
  {
    id: '4',
    title: 'Coke Run',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/coke-run.mp3',
  },
  {
    id: '5',
    title: 'Cokehead Jim',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/cokehead-jim.mp3',
  },
  {
    id: '6',
    title: 'Doggy Bone',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Doggy-Bone.mp3',
  },
  {
    id: '7',
    title: 'Fartron',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Fartron.mp3',
  },
  {
    id: '8',
    title: 'Hair Of The Pookie',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Hair-of-the-Pookie.mp3',
  },
  {
    id: '9',
    title: 'Hoebemian Rhapsody',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Hoebemian-rapsody.mp3',
  },
  {
    id: '10',
    title: 'Holy Hell',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/holy-hell.mp3',
  },
  {
    id: '11',
    title: 'In Flight Movie',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/In-Flight-Movie.mp3',
  },
  {
    id: '12',
    title: 'Magnetron',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Magnatron.mp3',
  },
  {
    id: '13',
    title: 'Mexican Coke',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Mexican-Coke.mp3',
  },
  {
    id: '14',
    title: 'Mississippi Mean',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Mississippi-Mean.mp3',
  },
  {
    id: '15',
    title: 'Moter Beard',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/moter-beard.mp3',
  },
  {
    id: '16',
    title: 'No Problems',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/No-Problems.mp3',
  },
  {
    id: '17',
    title: 'No Tequila',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/No-Tequlia.mp3',
  },
  {
    id: '18',
    title: 'Neutron Heavy',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Nutron-Heavy.mp3',
  },
  {
    id: '19',
    title: 'Pain Train',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Pain-Train.mp3',
  },
  {
    id: '20',
    title: 'Popular Vote',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Popular-vote.mp3',
  },
  {
    id: '21',
    title: 'Rock Bottom',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Rock-Bottom.mp3',
  },
  {
    id: '22',
    title: 'Saturday Night',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Saturday-Night.mp3',
  },
  {
    id: '23',
    title: 'Scarlett Box',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Scarlett-Box.mp3',
  },
  {
    id: '24',
    title: 'Shadows In The Dark',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Shadows-in-the-dark.mp3',
  },
  {
    id: '25',
    title: 'Spooky Knife',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/SpookyKnife.mp3',
  },
  {
    id: '26',
    title: 'Storms a Comin',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/Storms-a-comin.mp3',
  },
  {
    id: '27',
    title: 'We Need More Guitar',
    artist: 'Willy',
    album: 'Album One',
    year: '2025',
    file: 'https://robertwalker.tech/willyProductions/We-Need-More-Guitar.mp3',
  },
];
